services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    user: root # required for data persistence
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword123
      - GF_DEFAULT_INSTANCE_NAME=Grafana
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel
      - PROMETHEUS_INTERNAL_URL=http://prometheus:9090
  
  otel_collector:
    build:
      context: ./otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"

volumes: 
  prometheus_data:
  loki_data:
  grafana_data:
  tempo_data:
