apiVersion: 1
contactPoints:
  - orgId: 1
    name: Discord
    receivers:
      - uid: ffh7i1e1s20owa
        type: discord
        settings:
          avatar_url: ${DISCORD_AVATAR_URL}
          url: ${DISCORD_WEBHOOK_URL}
          use_discord_username: false
        disableResolveMessage: false
