receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:${env:OTLP_HTTP_PORT}"

exporters:
  prometheus:
    endpoint: "0.0.0.0:${env:PROMETHEUS_EXPORTER_PORT}"

  otlphttp/tempo:
    endpoint: "${env:TEMPO_ENDPOINT}"

  otlphttp/loki:
    endpoint: "${env:LOKI_ENDPOINT}"

processors:
  batch:

extensions:
  health_check:
    endpoint: "0.0.0.0:${env:HEALTH_CHECK_PORT}"

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
