receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:${env:OTLP_GRPC_PORT}"
      http:
        endpoint: "0.0.0.0:${env:OTLP_HTTP_PORT}"

exporters:
  debug:
  prometheus:
    endpoint: "0.0.0.0:${env:PROMETHEUS_EXPORTER_PORT}"

processors:
  batch:

extensions:
  health_check:
    endpoint: "0.0.0.0:${env:HEALTH_CHECK_PORT}"

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
