ARG VERSION=v3.5.1

FROM prom/prometheus:${VERSION}

USER root

COPY config.yaml /etc/prometheus/config.yaml.tmpl
COPY entrypoint.sh /entrypoint.sh

ENV OTEL_COLLECTOR_HOST=otel-collector.railway.internal
ENV OTEL_COLLECTOR_PORT=8889
ENV SCRAPE_INTERVAL=15s
ENV EVALUATION_INTERVAL=15s
ENV PORT=9090

ENTRYPOINT ["/entrypoint.sh"]
