apiVersion: 1

# prune: true removes datasources not defined here on startup
prune: true

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: grafana_prometheus
    url: http://${PROMETHEUS_HOST}:${PROMETHEUS_PORT}
    isDefault: true

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: grafana_tempo
    url: http://${TEMPO_HOST}:${TEMPO_PORT}

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: grafana_loki
    url: http://${LOKI_HOST}:${LOKI_PORT}
