{
 "title": "API - Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_success{service_name=\"API\", deployment_environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_time_seconds_total{service_name=\"API\", deployment_environment=\"$environment\"}[$__rate_interval])",
     "legendFormat": "{{cpu_mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memory_used_bytes{service_name=\"API\", deployment_environment=\"$environment\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total{deployment_environment=\"$environment\", service_name=\"API\"}[$__rate_interval])",
     "legendFormat": "{{network_io_direction}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{deployment_environment=\"$environment\", service_name=\"API\"}[$__rate_interval])) / (sum(rate(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_request_duration_seconds_bucket{deployment_environment=\"$environment\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_server_request_duration_seconds_bucket{deployment_environment=\"$environment\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_server_request_duration_seconds_bucket{deployment_environment=\"$environment\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request per Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(rate(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", service_name=\"API\"}[$__rate_interval])) * 60)[$__range:$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"1..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "1xx"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"2..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "2xx"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"3..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "3xx"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"4..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"5..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"API\", deployment_environment=\"$environment\"}"
    }
   ]
  }
 ]
}