{
 "title": "API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "runtime_uptime_milliseconds_total{deployment_environment=\"$environment\", service_name=\"API\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(system_cpu_time_seconds_total{service_name=\"API\", deployment_environment=\"$environment\", state!=\"idle\"}[$__rate_interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{deployment_environment=\"$environment\", service_name=\"API\", state=\"used\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total{deployment_environment=\"$environment\", service_name=\"API\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"API\", deployment_environment=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"1..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "1xx"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"2..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "2xx"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"3..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "3xx"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"4..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{deployment_environment=\"$environment\", http_response_status_code=~\"5..\", service_name=\"API\"}[$__rate_interval])))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(le) (increase(http_server_request_duration_seconds_bucket{deployment_environment=\"$environment\", service_name=\"API\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}