{
 "title": "App - Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime_seconds{service_name=\"App\", deployment_environment=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_utilization{service_name=\"App\", deployment_environment=\"$environment\"}",
     "legendFormat": "{{process_cpu_state}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage{service_name=\"App\", deployment_environment=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_total{service_name=\"App\", deployment_environment=\"$environment\"}[$__rate_interval])",
     "legendFormat": "{{network_io_direction}}"
    }
   ]
  }
 ]
}