{
 "title": "App",
 "description": "Frontend monitoring dashboard using metrics collected with Grafana Faro SDK.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{service_name=\"App\", deployment_environment=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "sum(process_cpu_utilization{service_name=\"App\", deployment_environment=\"$environment\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_memory_usage{service_name=\"App\", deployment_environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_total{service_name=\"App\", deployment_environment=\"$environment\"}[$__rate_interval])",
     "legendFormat": "{{network_io_direction}}"
    }
   ]
  },
  { "title": "Web Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Time to First Byte (TTFB)",
   "type": "stat",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.\nhttps://web.dev/ttfb/",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({service_name=\"App\", deployment_environment=\"$environment\"} |= `ttfb` | logfmt | kind = `measurement` | unwrap ttfb [$__range])"
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP)",
   "type": "stat",
   "description": "The First Contentful Paint (FCP) metric measures the time from when the page starts loading to when any part of the page's content is rendered on the screen. For this metric, \"content\" refers to text, images (including background images), <svg> elements, or non-white <canvas> elements.\nhttps://web.dev/fcp/",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({deployment_environment=\"$environment\", service_name=\"App\"} |= ` fcp=` | logfmt | kind = `measurement` | unwrap fcp [$__range])"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "stat",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({deployment_environment=\"$environment\", service_name=\"App\"} |= `cls` | logfmt | kind = `measurement` | unwrap cls [$__range])"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "stat",
   "description": "Largest Contentful Paint (LCP): measures loading performance. To provide a good user experience, LCP should occur within 2.5 seconds of when the page first starts loading.\nhttps://web.dev/lcp/",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({deployment_environment=\"$environment\", service_name=\"App\"} |= ` lcp=` | logfmt | kind = `measurement` | unwrap lcp [$__range])"
    }
   ]
  },
  {
   "title": "First Input Delay (FID)",
   "type": "stat",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({deployment_environment=\"$environment\", service_name=\"App\"} |= `input_delay=` | logfmt | kind = `measurement` | unwrap input_delay [$__range])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "options": {
    "content": "# Web Vitals\n\nFor Web Vitals help: [https://web.dev/vitals/](https://web.dev/vitals/)"
   }
  },
  {
   "title": "Page Load, p75",
   "type": "timeseries",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.\nhttps://web.dev/ttfb/",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {deployment_environment=\"$environment\", service_name=\"App\"} |= ` ttfb=` | logfmt | kind = `measurement` | unwrap ttfb [5m]) by (service_name)",
     "legendFormat": "ttfb"
    },
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {deployment_environment=\"$environment\",service_name=\"App\"} |= \" fcp=\" | logfmt | kind=\"measurement\" | unwrap fcp [5m]) by (service_name)",
     "legendFormat": "fcp"
    },
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {deployment_environment=\"$environment\",service_name=\"App\"} |= \" lcp=\" | logfmt | kind=\"measurement\" | unwrap lcp [5m]) by (service_name)",
     "legendFormat": "lcp"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift, p75",
   "type": "timeseries",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {deployment_environment=\"$environment\", service_name=\"App\"} |= ` cls=` | logfmt | kind = `measurement` | unwrap cls [5m]) by (service_name)",
     "legendFormat": "cls"
    }
   ]
  },
  {
   "title": "First Input Delay, p75",
   "type": "timeseries",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {deployment_environment=\"$environment\", service_name=\"App\"} |= `input_delay=` | logfmt | kind = `measurement` | unwrap input_delay [5m]) by (service_name)",
     "legendFormat": "fid"
    }
   ]
  },
  { "title": "Visits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Visits per Route",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "visits_total{deployment_environment=\"$environment\", service_name=\"App\"}",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Popular Browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count by(browser_name, browser_version) (count_over_time({deployment_environment=\"$environment\", service_name=\"App\"} |= ` ttfb=` | logfmt | kind = `measurement` [$__range])))"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (count_over_time({deployment_environment=\"$environment\", service_name=\"App\"} | logfmt | kind = `exception` [$__range]))"
    }
   ]
  },
  {
   "title": "Exceptions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({deployment_environment=\"$environment\", service_name=\"App\"} | logfmt | kind = `exception` [$__interval])"
    }
   ]
  },
  {
   "title": "Top Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count by(value) (count_over_time({deployment_environment=\"$environment\", service_name=\"App\"} | logfmt | kind = `exception` [$__range])))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Top URLs by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 41 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count by(page_url) (count_over_time({deployment_environment=\"$environment\", service_name=\"App\"} | logfmt | kind = `exception` [$__range])))",
     "legendFormat": "{{page_url}}"
    }
   ]
  },
  {
   "title": "Top Browsers by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 41 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count by(browser_name, browser_version) (count_over_time({deployment_environment=\"$environment\", service_name=\"App\"} | logfmt | kind = `exception` [$__range])))"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Top Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count by(event_name) (count_over_time({deployment_environment=\"$environment\", service_name=\"App\"} | logfmt | kind = `event` [$__range])))"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(50, count by(browser) (count_over_time({deployment_environment=\"$environment\", service_name=\"App\"} | logfmt | kind = `event` | event_name = `mainspa_mount` [$__range])))"
    }
   ]
  }
 ]
}