{
 "title": "RAG - Monitor",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_utilization_ratio{service_name=\"rag\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{service_name=\"rag\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_network_io_bytes_total{service_name=\"rag\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Cost per Organization",
   "type": "stat",
   "description": "LLM input token = $0.3 / 1M \nLLM output token = $2.5 / 1M\nEmbedding input token = $0.15 / 1M",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (org_id) (increase(llm_input_tokens_total{service_name=\"rag\"}[$__range])) / 1e6 * 0.3\n)\n+\n(\n  sum by (org_id) (increase(llm_output_tokens_total{service_name=\"rag\"}[$__range])) / 1e6 * 2.5\n)\n+\n(\n  sum by (org_id) (increase(embedding_input_tokens_total{service_name=\"rag\"}[$__range])) / 1e6 * 0.15\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total LLM Token Usage by Organization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (org_id) (increase(llm_input_tokens_total{service_name=\"rag\"}[$__range])) \n)\n+\n(\n  sum by (org_id) (increase(llm_output_tokens_total{service_name=\"rag\"}[$__range]))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (org_id) (increase(llm_output_tokens_total{service_name=\"rag\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (org_id) (increase(llm_input_tokens_total{service_name=\"rag\"}[$__range])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Embedding Token Usage by Organization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (org_id) (increase(embedding_input_tokens_total{service_name=\"rag\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}