{
 "title": "RAG",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (sum(temporal_num_pollers{service_name=\"rag\"}) == bool 0)\n  or\n  (time() - max(timestamp(temporal_num_pollers{service_name=\"rag\"})) > bool 30)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "process_cpu_utilization_ratio{service_name=\"rag\", deployment_environment=\"staging\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{service_name=\"rag\", deployment_environment=\"$environment\"}",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(direction) (rate(system_network_io_bytes_total{service_name=\"rag\", deployment_environment=\"$environment\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum(increase(llm_input_tokens_total{service_name=\"rag\", deployment_environment=\"$environment\"}[$__range]) * 0.3 / 1000000)) + (sum(increase(llm_output_tokens_total{service_name=\"rag\", deployment_environment=\"$environment\"}[$__range]) * 2.5 / 1000000)) + (sum(increase(embedding_input_tokens_total{service_name=\"rag\", deployment_environment=\"$environment\"}[$__range]) * 0.15 / 1000000))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation (Input)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "K" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(llm_input_tokens_total{service_name=\"rag\", deployment_environment=\"$environment\"}[$__range])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation (Output)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "K" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(llm_output_tokens_total{service_name=\"rag\", deployment_environment=\"$environment\"}[$__range]) / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Embedding",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "K" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(embedding_input_tokens_total{service_name=\"rag\", deployment_environment=\"$environment\"}[$__range])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}