{
 "title": "Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(probe_success,deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{deployment_environment=\"$environment\", service_name=\"App\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Uptime Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{deployment_environment=\"$environment\", service_name=\"API\"}[$__range])",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "group by(cloud_region) (last_over_time(target_info{deployment_environment=\"$environment\", job=\"App\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Status",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "probe_success{deployment_environment=\"$environment\", service_name=\"API\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Uptime Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{deployment_environment=\"$environment\", service_name=\"API\"}[$__range])",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "targets": [
    {
     "expr": "group by(cloud_region) (last_over_time(target_info{deployment_environment=\"$environment\", job=\"API\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAG",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "Status",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "temporal_worker_task_slots_used{deployment_environment=\"$environment\", service_name=\"RAG\", task_queue=\"rag\", worker_type=\"WorkflowWorker\"} > bool 0",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Uptime Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    temporal_worker_task_slots_used{service_name=\"RAG\", task_queue=\"rag\", deployment_environment=\"$environment\", worker_type=\"WorkflowWorker\"} > bool 0\n  )[$__range:]\n)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
   "targets": [
    {
     "expr": "group by(cloud_region) (last_over_time(target_info{deployment_environment=\"$environment\", job=\"RAG\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}