ARG VERSION=12.4.0

FROM grafana/grafana-oss:${VERSION}

USER root

COPY datasources /etc/grafana/provisioning/datasources
COPY dashboards /etc/grafana/provisioning/dashboards
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

ENV PORT=3000
ENV PROMETHEUS_HOST=prometheus.railway.internal
ENV PROMETHEUS_PORT=9090
ENV TEMPO_HOST=tempo.railway.internal
ENV TEMPO_PORT=3200
ENV LOKI_HOST=loki.railway.internal
ENV LOKI_PORT=3100

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
