[server]
# domain = ${DOMAIN}
# protocol = ${PROTOCOL}
# http_port = ${PORT}
root_url = ${ROOT_URL}

[auth.google]
enabled = true
client_id = ${AUTH_GOOGLE_CLIENT_ID}
client_secret = ${AUTH_GOOGLE_CLIENT_SECRET}
allowed_domains = ${AUTH_GOOGLE_ALLOWED_DOMAINS}
role_attribute_path = email == '${AUTH_GOOGLE_ADMIN_EMAIL}' && 'Admin' || (ends_with(to_string(email), '@${AUTH_GOOGLE_ALLOWED_DOMAINS}') && 'Editor' || 'Viewer')
role_attribute_strict = true
allow_assign_organization = true
auto_assign_org_role = Admin

[auth]
disable_login_form = true

[users]
allow_sign_up = false
