apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: grafana_prometheus
    url: http://${PROMETHEUS_HOST}:${PROMETHEUS_PORT}
    isDefault: true
