stream_over_http_enabled: true

server:
  http_listen_port: ${PORT:-3200}
  grpc_listen_port: 9095

distributor:
  log_received_spans:
    enabled: true
  receivers:
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:${OTLP_HTTP_PORT:-4318}"

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

compactor:
  compaction:
    compaction_window: 1h
